name: nlp
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - spacy
  - pytorch
  - transformers
  - datasets
